AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30



Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/MultipleComparison: 
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
